---
title: EnaTest
timezone: UTC
collections:
  artworks:
    title: Artworks
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: artworks
  values:
    layout: artwork
    permalink: "/artworks/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: artworks
  values:
    artwork year: 
    image: 
permalink: pretty
